### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by imerelli** [yangqianq/EpiCas-DL#1]
Hi, I'm testing your code, 
but I think a file Is missing from the repository:
/epi_reference/human_p1p2Table.txt
Could you please upload it?

**Comment by yangqianq** [comment]
Sorry for the our late reply, we have updated "Note" of README and provided the download link of "Epi_reference" folder.  You can download the folder via this link “https://pan.baidu.com/s/1TbUhdmaJ8b0vhUF1Tqhuqw?pwd=ilg1”.
Thank you for your attention. If you have any other questions, I will reply as soon as possible.
